In [3]:
import pandas as pd
df = pd.read_csv('Countries.csv')

In [ ]:
df.head()

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Population,Land,Continent Name,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density
0,Afghanistan,AFG,2000,27.501127,40.717968,13.670101,NaN,1.415197e+10,10.902580,NaN,...,19542982.0,652860.0,Asia,NaN,NaN,1.934589e+09,1.542930e+09,NaN,724.145910,29.934415
1,Afghanistan,AFG,2001,27.501127,40.717968,13.670101,NaN,1.415197e+10,10.902580,NaN,...,19688632.0,652860.0,Asia,NaN,NaN,1.934589e+09,1.542930e+09,NaN,718.788917,30.157510
2,Afghanistan,AFG,2002,38.627892,40.717968,13.670101,NaN,3.854235e+09,9.443391,NaN,...,21000256.0,652860.0,Asia,NaN,NaN,5.268779e+08,3.639705e+08,NaN,183.532775,32.166553
3,Afghanistan,AFG,2003,37.418855,40.717968,13.670101,NaN,4.539497e+09,8.941258,NaN,...,22645130.0,652860.0,Asia,NaN,NaN,6.205538e+08,4.058881e+08,NaN,200.462376,34.686043
4,Afghanistan,AFG,2004,29.721067,40.717968,13.670101,NaN,5.220825e+09,9.808474,NaN,...,23553551.0,652860.0,Asia,NaN,NaN,7.136921e+08,5.120832e+08,NaN,221.657662,36.077491

In [4]:
df.isnull().sum()

Country Name                        0
Country Code                        0
Year                                0
Agriculture (% GDP)               276
Ease of Doing Business            598
Education Expenditure (% GDP)     368
Export (% GDP)                    460
GDP                                69
Health Expenditure (% GDP)        575
Import (% GDP)                    460
Industry (% GDP)                  253
Inflation Rate                    552
R&D                              1518
Service (% GDP)                   299
Unemployment                      667
Population                          0
Land                                0
Continent Name                      0
Export                            460
Import                            460
Education Expenditure             414
Health Expenditure                575
Net Trade                         460
GDP Per Capita                     69
Population Density                  0
dtype: int64

In [ ]:
df.describe()

,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),Industry (% GDP),Inflation Rate,...,Unemployment,Population,Land,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density
count,5106.000000,4830.000000,4508.000000,4738.000000,4646.000000,5.037000e+03,4531.000000,4646.000000,4853.000000,4554.000000,...,4439.000000,5.106000e+03,5.106000e+03,4.646000e+03,4.646000e+03,4.692000e+03,4.531000e+03,4.646000e+03,5037.000000,5106.000000
mean,2011.000000,10.893914,61.738665,14.458547,44.018003,3.120245e+11,6.167133,49.445204,26.315490,6.991400,...,8.115195,3.282803e+07,7.003599e+05,9.505712e+10,9.248778e+10,4.304518e+10,3.214250e+10,2.569338e+09,15336.273219,336.020957
std,6.633899,10.971965,13.775267,4.984259,33.173984,1.405946e+12,2.744570,30.474001,12.924200,19.858123,...,5.888784,1.281141e+08,2.117451e+06,2.638186e+11,2.720004e+11,1.946240e+11,2.012357e+11,5.380235e+10,23831.258493,1570.547928
min,2000.000000,0.012519,19.977700,0.833360,1.571162,1.396473e+07,1.263576,1.127672,2.758632,-16.859691,...,0.095000,9.609000e+03,2.027000e+00,7.959988e+06,2.290063e+07,4.129775e+06,2.093155e+06,-9.540869e+11,110.460875,0.136492
25%,2005.000000,2.275972,52.919894,10.870940,23.544736,4.186073e+09,4.158750,29.401814,17.919508,1.599237,...,3.866000,8.049668e+05,1.130000e+04,1.827572e+09,2.510900e+09,6.457364e+08,2.687793e+08,-2.043559e+09,1564.015195,30.837607
50%,2011.000000,6.979923,61.982110,13.952830,36.438987,1.777477e+10,5.639608,42.543697,24.119251,3.466447,...,6.510000,5.897816e+06,9.895395e+04,8.541387e+09,9.727140e+09,3.064088e+09,1.286994e+09,-2.340244e+08,5396.214227,82.396143
75%,2017.000000,16.748657,72.535918,17.609406,54.543771,1.216041e+11,7.865923,60.600202,31.812769,7.288914,...,10.840000,2.123560e+07,4.881000e+05,6.026577e+10,5.282874e+10,1.958102e+10,7.609297e+09,1.859483e+09,19733.229269,195.721744
max,2022.000000,79.042362,87.166330,44.801800,433.836004,2.546270e+13,24.230680,429.359095,86.669555,557.201817,...,37.320000,1.417173e+09,1.709825e+07,3.714245e+12,3.874205e+12,3.667693e+12,3.966028e+12,5.766511e+11,234317.084818,23814.890701

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5106 entries, 0 to 5105
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country Name                   5106 non-null   object
 1   Country Code                   5106 non-null   object
 2   Year                           5106 non-null   int64
 3   Agriculture (% GDP)            4830 non-null   float64
 4   Ease of Doing Business         4508 non-null   float64
 5   Education Expenditure (% GDP)  4738 non-null   float64
 6   Export (% GDP)                 4646 non-null   float64
 7   GDP                            5037 non-null   float64
 8   Health Expenditure (% GDP)     4531 non-null   float64
 9   Import (% GDP)                 4646 non-null   float64
 10  Industry (% GDP)               4853 non-null   float64
 11  Inflation Rate                 4554 non-null   float64
 12  R&D                            3588 non-null   float64
 13  Service (% GDP)                4807 non-null   float64
 14  Unemployment                   4439 non-null   float64
 15  Population                     5106 non-null   float64
 16  Land                           5106 non-null   float64
 17  Continent Name                 5106 non-null   object
 18  Export                         4646 non-null   float64
 19  Import                         4646 non-null   float64
 20  Education Expenditure          4692 non-null   float64
 21  Health Expenditure             4531 non-null   float64
 22  Net Trade                      4646 non-null   float64
 23  GDP Per Capita                 5037 non-null   float64
 24  Population Density             5106 non-null   float64
dtypes: float64(21), int64(1), object(3)
memory usage: 997.4+ KB

In [ ]:
for column in df.columns:
    if df[column].isnull().sum() > 0:  # Check if the column has missing values
        skewness = df[column].skew()

        # If skewness is between -0.5 and 0.5, use the mean
        if -0.5 <= skewness <= 0.5:
            df[column] = df[column].fillna(df[column].mean())
        # If skewness is outside -0.5 to 0.5, use the median
        else:
            df[column] = df[column].fillna(df[column].median())

In [ ]:
print(df.isnull().sum())

Country Name                     0
Country Code                     0
Year                             0
Agriculture (% GDP)              0
Ease of Doing Business           0
Education Expenditure (% GDP)    0
Export (% GDP)                   0
GDP                              0
Health Expenditure (% GDP)       0
Import (% GDP)                   0
Industry (% GDP)                 0
Inflation Rate                   0
R&D                              0
Service (% GDP)                  0
Unemployment                     0
Population                       0
Land                             0
Continent Name                   0
Export                           0
Import                           0
Education Expenditure            0
Health Expenditure               0
Net Trade                        0
GDP Per Capita                   0
Population Density               0
dtype: int64

In [ ]:
# Check for duplicate rows
duplicate_rows = df.duplicated()
print(duplicate_rows.sum())  # This will print the number of duplicate rows

0

In [ ]:
usa_data = df[df['Country Name']== 'United States']
print(usa_data)

       Country Name Country Code  Year  Agriculture (% GDP)  \
4853  United States          USA  2000             1.150555
4854  United States          USA  2001             1.129257
4855  United States          USA  2002             0.973712
4856  United States          USA  2003             1.121048
4857  United States          USA  2004             1.265484
4858  United States          USA  2005             1.150507
4859  United States          USA  2006             1.009487
4860  United States          USA  2007             1.075124
4861  United States          USA  2008             1.053001
4862  United States          USA  2009             0.960286
4863  United States          USA  2010             1.029437
4864  United States          USA  2011             1.200559
4865  United States          USA  2012             1.149330
4866  United States          USA  2013             1.321084
4867  United States          USA  2014             1.172065
4868  United States          USA  2015             1.033934
4869  United States          USA  2016             0.942645
4870  United States          USA  2017             0.946869
4871  United States          USA  2018             0.903901
4872  United States          USA  2019             0.838813
4873  United States          USA  2020             0.948847
4874  United States          USA  2021             0.959567
4875  United States          USA  2022             1.060705

      Ease of Doing Business  Education Expenditure (% GDP)  Export (% GDP)  \
4853               83.668618                      14.404180       10.692777
4854               83.668618                      14.404180        9.703447
4855               83.668618                      14.404180        9.131382
4856               83.668618                      14.404180        9.035659
4857               83.668618                      14.404180        9.628750
4858               83.668618                      14.404180        9.982055
4859               83.668618                      14.404180       10.641386
4860               83.668618                      14.404180       11.463790
4861               83.668618                      14.404180       12.425847
4862               83.668618                      14.404180       10.932221
4863               83.668618                      15.567280       12.341361
4864               83.668618                      15.509571       13.563467
4865               83.668618                      15.600352       13.644049
4866               83.668618                      16.023888       13.578074
4867               83.668618                      16.003635       13.545959
4868               83.592470                      13.545640       12.460993
4869               83.589910                      13.154210       11.939539
4870               83.590080                      13.864670       12.261738
4871               83.573950                      13.146180       12.360989
4872               83.996680                      13.380550       11.872470
4873               83.668618                      12.650000       10.202126
4874               83.668618                      14.404180       10.892727
4875               83.668618                      14.404180       11.468218

               GDP  Health Expenditure (% GDP)  Import (% GDP)  ...  \
4853  1.025095e+13                   12.487109       14.410218  ...
4854  1.058193e+13                   13.164667       13.263734  ...
4855  1.092911e+13                   13.991673       13.154993  ...
4856  1.145644e+13                   14.501135       13.591654  ...
4857  1.221719e+13                   14.546637       14.819312  ...
4858  1.303920e+13                   14.574480       15.656498  ...
4859  1.381559e+13                   14.703585       16.333892  ...
4860  1.447423e+13                   14.914631       16.548228  ...
4861  1.476986e+13                   15.204899       17.441948  ...
4862  1.447806e+13                   16.198774       13.827311  ...
4863  1.504896e+13                   16.195580       15.878534  ...
4864  1.559973e+13                   16.137644       17.279019  ...
4865  1.625397e+13                   16.116940       17.037786  ...
4866  1.684319e+13                   15.986938       16.424293  ...
4867  1.755068e+13                   16.192408       16.452040  ...
4868  1.820602e+13                   16.481092       15.351240  ...
4869  1.869511e+13                   16.793148       14.647461  ...
4870  1.947734e+13                   16.767937       15.017423  ...
4871  2.053306e+13                   16.640944       15.249390  ...
4872  2.138098e+13                   16.676474       14.579479  ...
4873  2.106047e+13                   18.815826       13.181636  ...
4874  2.331508e+13                   15.575834       14.588674  ...
4875  2.546270e+13                   15.575834       15.215217  ...

       Population          Land  Continent Name        Export        Import  \
4853  282162411.0  9.632030e+06   North America  1.096111e+12  1.477184e+12
4854  284968955.0  9.632030e+06   North America  1.026812e+12  1.403559e+12
4855  287625193.0  9.632030e+06   North America  9.979790e+11  1.437724e+12
4856  290107933.0  9.632030e+06   North America  1.035165e+12  1.557120e+12
4857  292805298.0  9.632030e+06   North America  1.176363e+12  1.810504e+12
4858  295516599.0  9.632030e+06   North America  1.301580e+12  2.041482e+12
4859  298379912.0  9.632030e+06   North America  1.470170e+12  2.256623e+12
4860  301231207.0  9.632030e+06   North America  1.659295e+12  2.395228e+12
4861  304093966.0  9.831510e+06   North America  1.835280e+12  2.576151e+12
4862  306771529.0  9.831510e+06   North America  1.582774e+12  2.001927e+12
4863  309327143.0  9.831510e+06   North America  1.857247e+12  2.389555e+12
4864  311583481.0  9.831510e+06   North America  2.115864e+12  2.695480e+12
4865  313877662.0  9.831510e+06   North America  2.217700e+12  2.769317e+12
4866  316059947.0  9.831510e+06   North America  2.286981e+12  2.766375e+12
4867  318386329.0  9.831510e+06   North America  2.377408e+12  2.887445e+12
4868  320738994.0  9.831510e+06   North America  2.268651e+12  2.794850e+12
4869  323071755.0  9.831510e+06   North America  2.232110e+12  2.738359e+12
4870  325122128.0  9.831510e+06   North America  2.388260e+12  2.924994e+12
4871  326838199.0  9.831510e+06   North America  2.538089e+12  3.131166e+12
4872  328329953.0  9.831510e+06   North America  2.538450e+12  3.117235e+12
4873  331511512.0  9.831510e+06   North America  2.148616e+12  2.776115e+12
4874  332031554.0  9.755518e+06   North America  2.539648e+12  3.401361e+12
4875  333287557.0  9.755518e+06   North America  2.920118e+12  3.874205e+12

      Education Expenditure  Health Expenditure     Net Trade  GDP Per Capita  \
4853           1.476565e+12        1.280047e+12 -3.810730e+11    36329.956073
4854           1.524240e+12        1.393076e+12 -3.767470e+11    37133.623113
4855           1.574249e+12        1.529166e+12 -4.397450e+11    37997.759657
4856           1.650206e+12        1.661314e+12 -5.219550e+11    39490.274956
4857           1.759786e+12        1.777191e+12 -6.341410e+11    41724.631629
4858           1.878190e+12        1.900395e+12 -7.399020e+11    44123.407068
4859           1.990022e+12        2.031387e+12 -7.864530e+11    46302.000880
4860           2.084894e+12        2.158778e+12 -7.359330e+11    48050.223777
4861           2.127477e+12        2.245742e+12 -7.408710e+11    48570.045980
4862           2.085446e+12        2.345269e+12 -4.191530e+11    47194.943355
4863           2.342714e+12        2.437267e+12 -5.323080e+11    48650.643128
4864           2.419451e+12        2.517429e+12 -5.796160e+11    50065.966504
4865           2.535677e+12        2.619643e+12 -5.516170e+11    51784.418574
4866           2.698934e+12        2.692711e+12 -4.793940e+11    53291.127689
4867           2.808747e+12        2.841878e+12 -5.100370e+11    55123.849787
4868           2.466122e+12        3.000551e+12 -5.261990e+11    56762.729452
4869           2.459194e+12        3.139498e+12 -5.062490e+11    57866.744934
4870           2.700468e+12        3.265947e+12 -5.367340e+11    59907.754261
4871           2.699313e+12        3.416894e+12 -5.930770e+11    62823.309438
4872           2.860892e+12        3.565593e+12 -5.787850e+11    65120.394663
4873           2.664150e+12        3.962702e+12 -6.274990e+11    63528.634303
4874           3.358346e+12        3.631518e+12 -8.617130e+11    70219.472454
4875           3.667693e+12        3.966028e+12 -9.540869e+11    76398.591742

      Population Density
4853           29.294179
4854           29.585555
4855           29.861327
4856           30.119085
4857           30.399126
4858           30.680614
4859           30.977884
4860           31.273907
4861           30.930545
4862           31.202890
4863           31.462832
4864           31.692332
4865           31.925682
4866           32.147650
4867           32.384276
4868           32.623574
4869           32.860848
4870           33.069399
4871           33.243947
4872           33.395679
4873           33.719287
4874           34.035257
4875           34.164005

[23 rows x 25 columns]

In [ ]:
df.to_csv('processed_countries_data.csv', index=False)